In [1]:
import pandas as pd

filename = 'chicago.csv'

# load data file into a dataframe
df = pd.read_csv(filename)

# convert the Start Time column to datetime
df['Start Time'] = pd.to_datetime(df['Start Time'] )

# extract hour from the Start Time column to create an hour column
df['hour'] = df['Start Time'].dt.hour

# find the most common hour (from 0 to 23)
popular_hour = df['hour'].mode()[0]
    
print('Most Frequent Start Hour:', popular_hour)

Most Frequent Start Hour: 17

In [20]:
df.head(5)

,Unnamed: 0,Start Time,End Time,Trip Duration,Start Station,End Station,User Type,Gender,Birth Year,hour
0,1423854,2017-06-23 15:09:32,2017-06-23 15:14:53,321,Wood St & Hubbard St,Damen Ave & Chicago Ave,Subscriber,Male,1992.0,15
1,955915,2017-05-25 18:19:03,2017-05-25 18:45:53,1610,Theater on the Lake,Sheffield Ave & Waveland Ave,Subscriber,Female,1992.0,18
2,9031,2017-01-04 08:27:49,2017-01-04 08:34:45,416,May St & Taylor St,Wood St & Taylor St,Subscriber,Male,1981.0,8
3,304487,2017-03-06 13:49:38,2017-03-06 13:55:28,350,Christiana Ave & Lawrence Ave,St. Louis Ave & Balmoral Ave,Subscriber,Male,1986.0,13
4,45207,2017-01-17 14:53:07,2017-01-17 15:02:01,534,Clark St & Randolph St,Desplaines St & Jackson Blvd,Subscriber,Male,1975.0,14

In [7]:
if df['Gender'] is True:
    print ('hi')
else:
    print('No')

No

In [32]:
df['Birth Year'].min()

1899.0

In [28]:
(df['Start Station'].mode() ) + ((df['End Station']).mode())

0    Streeter Dr & Grand AveStreeter Dr & Grand Ave
dtype: object

In [ ]:
df['Start Station'].zip

In [37]:


df['Birth Year'].min()

1899.0

In [ ]:
import pandas as pd

filename = 'chicago.csv'

# load data file into a dataframe
df = pd.read_csv(filename)

# print value counts for each user type
user_types = df['User Type'].value_counts()

print(user_types)

In [38]:
import pandas as pd

CITY_DATA = { 'chicago': 'chicago.csv',
              'new york city': 'new_york_city.csv',
              'washington': 'washington.csv' }

def load_data(city, month, day):
    """
    Loads data for the specified city and filters by month and day if applicable.

    Args:
        (str) city - name of the city to analyze
        (str) month - name of the month to filter by, or "all" to apply no month filter
        (str) day - name of the day of week to filter by, or "all" to apply no day filter
    Returns:
        df - Pandas DataFrame containing city data filtered by month and day
    """

    # load data file into a dataframe
    df = pd.read_csv(CITY_DATA[city])

    # convert the Start Time column to datetime
    df['Start Time'] = pd.to_datetime(df['Start Time'])

    # extract month and day of week from Start Time to create new columns
    df['month'] = df['Start Time'].dt.month
    df['day_of_week'] = df['Start Time'].dt.weekday_name

    # filter by month if applicable
    if month != 'all':
        # use the index of the months list to get the corresponding int
        months = ['january', 'february', 'march', 'april', 'may', 'june']
        month = months.index(month) + 1

        # filter by month to create the new dataframe
        df = df[df['month'] == month]

    # filter by day of week if applicable
    if day != 'all':
        # filter by day of week to create the new dataframe
        df = df[df['day_of_week'] == day.title()]

    return df
df = load_data('chicago', 'march', 'friday')

In [39]:
df

,Unnamed: 0,Start Time,End Time,Trip Duration,Start Station,End Station,User Type,Gender,Birth Year,month,day_of_week
37,395803,2017-03-24 15:35:55,2017-03-24 15:46:10,615,Dearborn St & Erie St,State St & Van Buren St,Subscriber,Male,1989.0,3,Friday
93,395735,2017-03-24 15:32:04,2017-03-24 15:52:53,1249,Sedgwick St & Webster Ave,Western Ave & Winnebago Ave,Subscriber,Female,1964.0,3,Friday
175,395402,2017-03-24 15:10:29,2017-03-24 15:19:44,555,Franklin St & Monroe St,Aberdeen St & Monroe St,Subscriber,Male,1987.0,3,Friday
190,393400,2017-03-24 12:29:30,2017-03-24 12:48:56,1166,Southport Ave & Wellington Ave,Lake Shore Dr & North Blvd,Subscriber,Female,1984.0,3,Friday
198,427496,2017-03-31 08:25:53,2017-03-31 08:39:09,796,Clinton St & Jackson Blvd,Racine Ave (May St) & Fulton St,Subscriber,Male,1983.0,3,Friday
232,391555,2017-03-24 08:41:22,2017-03-24 08:50:16,534,Clinton St & Washington Blvd,Financial Pl & Congress Pkwy,Subscriber,Male,1963.0,3,Friday
248,334159,2017-03-10 22:17:28,2017-03-10 22:37:53,1225,Damen Ave & Augusta Blvd,Lincoln Ave & Diversey Pkwy,Subscriber,Male,1988.0,3,Friday
251,393341,2017-03-24 12:24:00,2017-03-24 12:53:25,1765,Streeter Dr & Grand Ave,Clark St & Armitage Ave,Customer,NaN,NaN,3,Friday
297,351986,2017-03-17 06:18:10,2017-03-17 06:25:06,416,Clinton St & Madison St,State St & Van Buren St,Subscriber,Male,1960.0,3,Friday
311,428458,2017-03-31 12:19:26,2017-03-31 12:36:56,1050,McCormick Place,Daley Center Plaza,Subscriber,Male,1985.0,3,Friday
454,393827,2017-03-24 13:08:08,2017-03-24 13:53:04,2696,Lake Shore Dr & Ohio St,Lake Shore Dr & Ohio St,Customer,NaN,NaN,3,Friday
460,356164,2017-03-17 19:24:31,2017-03-17 19:42:01,1050,St. Clair St & Erie St,Larrabee St & Armitage Ave,Subscriber,Male,1989.0,3,Friday
497,331491,2017-03-10 13:19:34,2017-03-10 13:46:03,1589,Clinton St & Madison St,Clark St & 9th St (AMLI),Subscriber,Male,1982.0,3,Friday
533,329259,2017-03-10 06:30:32,2017-03-10 06:33:02,150,Western Ave & Winnebago Ave,Leavitt St & North Ave,Subscriber,Male,1985.0,3,Friday
542,428966,2017-03-31 14:34:50,2017-03-31 14:41:50,420,Clark St & Randolph St,Clinton St & Jackson Blvd,Subscriber,Male,1986.0,3,Friday
617,356311,2017-03-17 20:10:28,2017-03-17 20:17:11,403,Dayton St & North Ave,Wells St & Concord Ln,Subscriber,Male,1991.0,3,Friday
654,396543,2017-03-24 16:12:17,2017-03-24 16:31:03,1126,Streeter Dr & Grand Ave,Theater on the Lake,Subscriber,Male,1994.0,3,Friday
696,427323,2017-03-31 08:09:10,2017-03-31 08:15:55,405,Aberdeen St & Jackson Blvd,Franklin St & Jackson Blvd,Subscriber,Male,1986.0,3,Friday
698,333750,2017-03-10 18:52:50,2017-03-10 19:00:00,430,Orleans St & Merchandise Mart Plaza,Dearborn St & Erie St,Subscriber,Male,1988.0,3,Friday
734,289917,2017-03-03 11:26:09,2017-03-03 11:41:41,932,Dusable Harbor,Field Museum,Customer,NaN,NaN,3,Friday
803,329433,2017-03-10 07:07:28,2017-03-10 07:12:53,325,Clarendon Ave & Gordon Ter,Sheridan Rd & Irving Park Rd,Subscriber,Female,1989.0,3,Friday
916,431326,2017-03-31 20:04:39,2017-03-31 20:08:53,254,Kingsbury St & Kinzie St,Clinton St & Washington Blvd,Subscriber,Male,1964.0,3,Friday
934,289469,2017-03-03 09:09:21,2017-03-03 09:18:38,557,Canal St & Adams St,Clinton St & Lake St,Subscriber,Female,1977.0,3,Friday
981,431436,2017-03-31 20:49:03,2017-03-31 21:01:49,766,Desplaines St & Kinzie St,Desplaines St & Kinzie St,Subscriber,Female,1995.0,3,Friday
1013,397792,2017-03-24 17:02:51,2017-03-24 17:17:49,898,Stockton Dr & Wrightwood Ave,Halsted St & Dickens Ave,Subscriber,Female,1984.0,3,Friday
1089,329892,2017-03-10 07:59:51,2017-03-10 08:05:45,354,Millennium Park,LaSalle St & Adams St,Subscriber,Male,1962.0,3,Friday
1145,397184,2017-03-24 16:38:40,2017-03-24 16:42:51,251,Southport Ave & Roscoe St,Southport Ave & Irving Park Rd,Subscriber,Male,1991.0,3,Friday
1167,329576,2017-03-10 07:25:53,2017-03-10 07:29:31,218,Wilton Ave & Diversey Pkwy,Lincoln Ave & Fullerton Ave,Subscriber,Female,1994.0,3,Friday
1184,355303,2017-03-17 17:27:33,2017-03-17 17:29:44,131,Ravenswood Ave & Irving Park Rd,Ashland Ave & Belle Plaine Ave,Subscriber,Male,1989.0,3,Friday
1222,389872,2017-03-24 04:45:58,2017-03-24 04:56:49,651,Dayton St & North Ave,Elston Ave & Wabansia Ave,Subscriber,Male,1964.0,3,Friday
...,...,...,...,...,...,...,...,...,...,...,...
298441,354234,2017-03-17 15:31:27,2017-03-17 15:55:30,1443,Shedd Aquarium,Streeter Dr & Grand Ave,Customer,NaN,NaN,3,Friday
298463,428074,2017-03-31 10:06:54,2017-03-31 10:33:33,1599,Burnham Harbor,Lake Park Ave & 47th St,Customer,NaN,NaN,3,Friday
298495,288080,2017-03-03 05:36:09,2017-03-03 05:51:11,902,Canal St & Adams St,State St & Pearson St,Subscriber,Male,1951.0,3,Friday
298512,292652,2017-03-03 19:01:20,2017-03-03 19:10:58,578,LaSalle St & Washington St,Aberdeen St & Jackson Blvd,Subscriber,Male,1958.0,3,Friday
298538,354251,2017-03-17 15:34:35,2017-03-17 15:49:20,885,Halsted St & Roosevelt Rd,Clinton St & Washington Blvd,Subscriber,Male,1966.0,3,Friday
298590,393953,2017-03-24 13:20:17,2017-03-24 13:56:45,2188,Lake Shore Dr & Belmont Ave,Lake Shore Dr & North Blvd,Subscriber,Female,1992.0,3,Friday
298600,392389,2017-03-24 10:29:10,2017-03-24 10:35:15,365,Benson Ave & Church St,Sheridan Rd & Noyes St (NU),Subscriber,Male,1983.0,3,Friday
298650,332161,2017-03-10 15:56:44,2017-03-10 16:03:05,381,Franklin St & Jackson Blvd,Clinton St & Madison St,Subscriber,Male,1952.0,3,Friday
298695,329485,2017-03-10 07:15:03,2017-03-10 07:20:45,342,Clark St & Grace St,Wilton Ave & Belmont Ave,Subscriber,Male,1993.0,3,Friday
298754,430358,2017-03-31 17:35:29,2017-03-31 17:40:43,314,Avondale Ave & Irving Park Rd,Kilbourn Ave & Irving Park Rd,Subscriber,Female,1982.0,3,Friday
298770,355957,2017-03-17 18:46:53,2017-03-17 18:53:44,411,Damen Ave & Pierce Ave,Wood St & Division St,Subscriber,Female,1989.0,3,Friday
299052,397856,2017-03-24 17:04:59,2017-03-24 17:37:57,1978,LaSalle St & Illinois St,Lincoln Ave & Belle Plaine Ave,Customer,NaN,NaN,3,Friday
299097,329197,2017-03-10 06:13:00,2017-03-10 06:18:47,347,Wells St & Polk St,Dearborn St & Monroe St,Subscriber,Female,1988.0,3,Friday
299111,329540,2017-03-10 07:22:22,2017-03-10 07:24:19,117,Calumet Ave & 18th St,Michigan Ave & 18th St,Subscriber,Female,1985.0,3,Friday
299135,395800,2017-03-24 15:35:50,2017-03-24 15:41:58,368,Cottage Grove Ave & 43rd St,Prairie Ave & 43rd St,Subscriber,Female,1962.0,3,Friday
299277,353476,2017-03-17 11:49:01,2017-03-17 11:54:09,308,Clinton St & Jackson Blvd,Canal St & Taylor St,Subscriber,Male,1977.0,3,Friday
299390,399789,2017-03-24 20:59:19,2017-03-24 21:10:15,656,Leavitt St & Archer Ave,Leavitt St & Archer Ave,Customer,NaN,NaN,3,Friday
299430,392985,2017-03-24 11:53:38,2017-03-24 12:05:16,698,Morgan Ave & 14th Pl,Green St & Randolph St,Subscriber,Male,1987.0,3,Friday
299433,355107,2017-03-17 17:12:24,2017-03-17 17:24:00,696,Franklin St & Monroe St,Wabash Ave & Grand Ave,Subscriber,Male,1993.0,3,Friday
299528,428442,2017-03-31 12:12:13,2017-03-31 12:18:31,378,Michigan Ave & Jackson Blvd,Daley Center Plaza,Subscriber,Male,1972.0,3,Friday
299548,397051,2017-03-24 16:33:45,2017-03-24 16:45:53,728,Clark St & Lincoln Ave,Broadway & Barry Ave,Subscriber,Male,1970.0,3,Friday
299569,391358,2017-03-24 08:29:50,2017-03-24 08:38:59,549,Canal St & Adams St,Wells St & Huron St,Subscriber,Male,1968.0,3,Friday
299598,351944,2017-03-17 06:03:35,2017-03-17 06:13:20,585,Racine Ave & Congress Pkwy,Clinton St & Jackson Blvd,Subscriber,Male,1953.0,3,Friday
299746,353725,2017-03-17 13:09:52,2017-03-17 13:22:17,745,Wabash Ave & Grand Ave,Sangamon St & Washington Blvd (*),Subscriber,Male,1993.0,3,Friday
299771,390676,2017-03-24 07:43:53,2017-03-24 07:53:26,573,LaSalle St & Illinois St,Columbus Dr & Randolph St,Subscriber,Male,1987.0,3,Friday
299816,333246,2017-03-10 17:40:53,2017-03-10 17:44:59,246,Wells St & Walton St,Rush St & Cedar St,Subscriber,Female,1992.0,3,Friday
299839,392682,2017-03-24 11:17:50,2017-03-24 11:51:44,2034,Lake Shore Dr & Monroe St,Streeter Dr & Grand Ave,Customer,NaN,NaN,3,Friday
299860,290125,2017-03-03 12:19:29,2017-03-03 12:32:58,809,Aberdeen St & Monroe St,Clark St & 9th St (AMLI),Subscriber,Male,1975.0,3,Friday
299865,288513,2017-03-03 07:26:48,2017-03-03 07:31:22,274,Damen Ave & Melrose Ave,Lincoln Ave & Roscoe St,Subscriber,Female,1981.0,3,Friday
299898,292757,2017-03-03 19:30:48,2017-03-03 19:34:52,244,Clark St & Berwyn Ave,Broadway & Berwyn Ave,Subscriber,Male,1980.0,3,Friday